mkdir intermediates
cd intermediates
mkdir cyclone_coordinates
mkdir db
mkdir detectnodes
mkdir era5
mkdir era5_mslp
mkdir seaice_concentrations
mkdir shapes
mkdir shapes/sentinel1
mkdir shapes/swot
mkdir swot
mkdir stitchnodes
mkdir te_out
mkdir tempestextreme_files
mkdir tempestextreme_files/logs
mkdir tiffs
mkdir uuids