mkdir intermediates
cd intermediates
mkdir cyclone_coordinates
mkdir db
mkdir seaice_concentrations
mkdir shapes
mkdir shapes/sentinel1
mkdir tiffs
mkdir uuids
mkdir era5_mslp
mkdir tempestextreme_files
mkdir tempestextreme_files/logs